# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nathangoshay
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: present-pals-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: present-pals-backend

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handlers.demoHandler.hello
    events:
      - httpApi:
          path: /
          method: get
  """
  ingress lambdas:
    - signup handler: sign up for new account (should be immediate)
    - login handler: log into existing account (should be immediate)
    - claimed product handler: claim a product  (can be queued)
    - follow user handler: follow a user  (can be queued)
    - see my claimed products: look at products I've claimed for others


  immediate lambdas
    - get wishlist data
    - get product data
  """
