# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nathangoshay
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: present-pals-app
# "service" is the name of this project. This will also be added to your AWS resource names.
service: present-pals-backend

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handlers.demoHandler.hello
    events:
      - httpApi:
          path: /
          method: get
